[build-system]
requires = ["setuptools>=80.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jahus-mdml"
version = "0.2.0"
description = "MDML parser and generator"
authors = [{ name = "DarthJahus" }]
dependencies = []
